INSERT INTO users (username)
VALUES
    ("Viet Tran"),
    ("Tom Palin"),
    ("Tom Brock"),
    ("Ruan Pienaar"),
    ("Rowan Duguid"),
    ("Robby Raschke"),
    ("Ollie Gordon"),
    ("Natinael Neggatu"),
    ("Matt Skeoch"),
    ("Justin Worrall"),
    ("Jo Myhrvold"),
    ("Joe Bryan"),
    ("Jason Flanagan"),
    ("Jake Garlick"),
    ("Jack Walker"),
    ("Jack McKay Fletcher"),
    ("Isaac Rolph"),
    ("Fred Miles"),
    ("Ewan Nisbet"),
    ("Ben Gross"),
    ("Bakhtiiar Muzakparov"),
    ("Ashley Yeo"),
    ("Adam Shaw");